name: Metric Tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: '1.22'

            - name: Run tests with coverage
              run: go test ./... -coverprofile=coverage.out

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v2
              with:
                  file: coverage.out
                  flags: unittests
                  name: codecov-umbrella

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4.0.1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
